### PR TITLE
Add Onboarding

### LINKED ISSUE #58: Improve onboarding
full

### PR DESCRIPTION
**Pull request by 3lvis**
https://bakkenbaeck.wake.com/13136

closes #58

### CODE REVIEW

**Comment by aashishdhawan** [comment]
@3lvis  Apologies, i was just curious and added few comments. I hope this does not disturb your work flow (especially when PR is marked as WIP).

**Comment by 3lvis** [comment]
@aashishdhawan hi! Feedback is always welcomed :). I don't see any of your comments, though.

**Comment by 3lvis** [comment]
@marijnschilling can you check why the CI is failing?

**Comment by marijnschilling** [comment]
¯\_(ツ)_/¯
screenshot 2017-01-17 13 36 06

**Comment by 3lvis** [comment]
@marijnschilling It says that the font is missing https://circleci.com/gh/bakkenbaeck/daylight-ios/205?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by marijnschilling** [comment]
Huh? What font? I don't see anything about a font in the link you posted.

Don't we use the custom font for the version here?

**Comment by 3lvis** [comment]
We need to remove the font from the open source app so the project can build.

screen shot 2017-01-17 at 13 41 06

**Pull request merged**
